/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonColor } from "./components/my-button/my-button";
export namespace Components {
    interface MyButton {
        /**
          * The button color
         */
        "color": ButtonColor;
        /**
          * To disable button
         */
        "disabled": boolean;
    }
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        /**
          * The button color
         */
        "color"?: ButtonColor;
        /**
          * To disable button
         */
        "disabled"?: boolean;
        /**
          * Emitted when button is clicked
         */
        "onOnClick"?: (event: CustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "my-button": MyButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
        }
    }
}
